### PR TITLE
KeyboardEvent made Cypress e2e tests to fail

### PR DESCRIPTION
**Pull request by k3ira**
After bumping version to 2.2.1, we spotted an issue with cypress here:
https://github.com/SAITS/use-keyboard-shortcuts/pull/17/files#diff-38682f47b0cf12c516bc3714fc45d0fdL125

Cypress uses Event for keyboard events, and this was turning writing into false and the keyboard events were prevented, so typing didn't happen and tests failed.

Typescript didn't like `event.hasOwnProperty('code')` so I used `prop in obj` instead, although it's less safe, but didn't want to use `@ts-ignore`. What do you think? Would it be better to use hasOwnProperty and add `@ts-ignore`.?

### CODE REVIEW

**Comment by DanAndreasson** [comment]
Maybe add a test case for it so we don’t accidentally break cypress integration in the future? 🎉

**Comment by k3ira** [comment]
Yeah! Will do! Thanks @DanAndreasson :)

**Comment by DanAndreasson** [comment]
@k3ira should I merge without the tests? :)

**Comment by k3ira** [comment]
Hey @DanAndreasson! Hope you had nice holidays! :)
Will add tests tomorrow to this so we can close it properly.
We miss you here! 😢

**Comment by DanAndreasson** [comment]
@k3ira Had some excellent time off - was really nice! Hope you had nice holidays as well :D I plan on visiting next week on Wednesday 😁

Alright, then I'll await the tests!

**Comment by k3ira** [comment]
Glad you had a good vacation. Looking forward to seeing you on Wednesday! 😃
Added a test for the whole input case.

**Pull request merged**
